project:
  type: website
  resources:
    - exercises.zip
  render:
    - "*.qmd"
    - "!exercises/"
  
website:
  page-navigation: true
  title: "From R Markdown to Quarto"
  description: "ASA Traveling Workshop, cincinnati Chapter"
  
  repo-url: https://github.com/asa-quarto/website
  repo-actions: [edit, issue]
 
  open-graph: true
  
  sidebar:
    logo: "images/logo.png"
    pinned: true
    align: center
    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - text: "---"
      - section: "In the Morning"
        contents:
          - href: 1-rmarkdown-quarto/index.qmd
            text: From R Markdow to Quarto
          - href: 2-documents-slides/index.qmd
            text: Documents and slides
      - text: "---"
      - section: "In the Afternoon"
        contents:
          - href: 3-websites-books/index.qmd
            text: Websites and books
          - href: 4-manuscripts/index.qmd
            text: Manuscripts
 
  page-footer:
    left: "&copy; Copyright 2024, Mine Çetinkaya-Rundel + Andrew Bray + Charlotte Wickham"
    center:
      - icon: github
        href: https://github.com/orgs/asa-quarto/repositories
    right: "This page is built with 🖤 and [Quarto](https://quarto.org/)."
    background: "#b61e2e" # RedHawk red

            
format:
  html:
    theme:
      light: style/quarto-asa-light.scss
      dark: style/quarto-asa-dark.scss
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    toc: true
  revealjs:
    author:
      - "Mine Çetinkaya Rundel"
      - "Andrew Bray"
      - "Charlotte Wickham"
    institute:
      - "Duke University + Posit"
      - "UC Berkeley"
      - "Posit"
    transition: fade
    slide-number: true
    chalkboard: false
    logo: "../images/logo.png"
    theme: style/slides.scss
    footer: "[mine.quarto.pub/cincinnati-asa](https://mine.quarto.pub/cincinnati-asa)"

execute:
  freeze: auto
  echo: true