---
title: "From R Markdown to Quarto"
subtitle: "ASA Travelling Workshop, Kansas City Chapter"
format:
  html:
    toc: false
---

> 8:00 am - 1:00 pm\
> Thursday, October 3^rd^, 2024

Quarto is an open-source scientific and technical publishing system that offers multilingual programming language support to create dynamic and static documents, books, presentations, blogs, and other online resources. In this workshop, you will learn how to apply your reproducible authoring skills to the Quarto format and learn about new tools and workflows for authoring with Quarto in RStudio. You will learn to create static documents as well as slide presentations. The workshop will also introduce you to Quarto projects which you can use to build websites and write blogs and books. Finally, you will learn various ways to deploy and publish your Quarto projects on the web.

:::{.columns}

:::{.column width="50%"}
#### Producing a Single Document with Quarto

| Time          | Module                                      |
|---------------|---------------------------------------------|
| 8:00 - 9:00 | [R Markdown to Quarto](1-rmarkdown-quarto/) |
| 9:00 - 9:10 | Break                                       |
| 9:10 - 11:00 | [Documents and slides](2-documents-slides/) |
| 11:00 - 11:10 | Break                                       |

: {tbl-colwidths="\[25,35\]"}

:::

:::{.column width="50%"}
#### Producing Presentations and Websites

| Time          | Module                                 |
|---------------|----------------------------------------|
| 11:10 - 12:30 | [Websites and book](3-websites-books/) |
| 12:30 - 1:00  | [Manuscripts](4-manuscripts/)          |
| 1:00 - 2:00 | Lunch                                  |
| 2:00 | Keynote: Closeread                        |

: {tbl-colwidths="\[25,35\]"}

:::
:::

## Instructors

[Mine Çetinkaya-Rundel](https://mine-cr.com) is Professor of the Practice at Duke University and Developer Educator at RStudio. Mine’s work focuses on innovation in statistics and data science pedagogy, with an emphasis on computing, reproducible research, student-centered learning, and open-source education as well as pedagogical approaches for enhancing retention of women and under-represented minorities in STEM. Mine is a Fellow of the ASA and Elected Member of the ISI as well as the winner of the 2021 Robert V. Hogg Award for For Excellence in Teaching Introductory Statistics.

[Andrew Bray](https://github.com/andrewpbray) is an Associate Teaching Professor in the Department of Statistics at UC Berkeley, where he develops and teaches courses in statistics and data science. His research interests include statistical computing, data privacy, and applications of statistical models to environmental science. He is one of the authors of the infer R package for resampling based inference and an enthusiastic user of all things R Markdown / Quarto.

[Charlotte Wickham](https://www.cwick.co.nz/) (she/her) is a Developer Educator at Posit. As part of her job at Posit, Charlotte helps to keep [quarto.org](http://quarto.org)—a website about, and also built with, Quarto—up to date. Prior to Posit, she taught Statistics and Data Science at Oregon State University where she received awards for her in-person and online teaching.

The materials for this workshop were authored by the authors and  supported by the [ASA Traveling Course](https://community.amstat.org/coc/chapterresources/travelingcourse) program. This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).
